print('online feature1')
print('online feature2')
print('online feature3')
print('local changes1')
print('local changes2')
print('local changes13')
print('online feature 7')
print('online feature 8')
print('online feature 9')
